#!/bin/bash

# Alustaa versionhallinan
if [ "$1" = "init" ]; then
  if [ -d ".ohtuv" ]; then
    echo "[*WARNING*] Versionhallinta on jo alustettu"
  else
    mkdir .ohtuv
    echo "[*SUCCESS*] Versionhallinta alustettiin kansioon '.ohtuv'"
  fi

# Lisää tiedoston versionhallintaan
elif [ "$1" = "save" ]; then
  if [ -f "$2" ]; then
    dir="$PWD"
    orig="$PWD/$2"
    until [ "$PWD" = "/home" ]; do
      if [ -d ".ohtuv" ]; then
        cp $orig "$PWD/.ohtuv/$(date +%Y%m%d%H%M%S)_$2"
        echo $dir >> "$PWD/.ohtuv/$(date +%Y%m%d%H%M%S)_$2.source"
        echo "[*SUCCESS*] $2 lisättiin versionhallintaan nimellä $(date +%Y%m%d%H%M%S)_$2"
        exit
      fi
      cd ..
    done
    echo "[*ERROR*] Versionhallintaa ei löytynyt hakemistosta"
    echo "[*HINT*] Alusta versionhallinta komennolla 'ohtuv init'"
  else
    echo "[*ERROR*] Tiedostoa '$2' ei löytynyt"
  fi

# Palauttaa tiedoston versionhallinnasta
elif [ "$1" = "restore" ]
  then
    if [ "$2" ] && [ "$3" ]; then
      dir="$PWD"
      orig="$PWD/$2"
      until [ "$PWD" = "/home" ]; do
        if [ -d ".ohtuv" ]; then
          cd .ohtuv

          # Haetaan tiedostot versionhallinnasta
          file_list=()
          while IFS= read -d $'\0' -r file ; do
            file_list=("${file_list[@]}" "`echo $file | sed 's|./||'`")
          done < <(find . -regextype posix-extended -regex "./$2.*_$3*" -type f -print0)

		      if [ ${#file_list[@]} = 0 ]; then
            echo "[*ERROR*] Yhtään tiedosta ei löytynyt"

          elif ((${#file_list[@]} > 1)); then
            echo "[*WARNING*] Löydettiin enemmän kuin yksi. Rajaa tulosta."
           	for file in $file_list; do 
				      echo $file
			      done

          else
            cp "${file_list[0]}" "`cat ${file_list[0]}.source`/$3"
			      echo "[*SUCCESS*] Tiedosto palautettiin versionhallinnasta onnistuneesti"
			      echo "$file_list[0] >> `cat ${file_list[0]}.source`/$3"
          fi
          exit
        fi
        cd ..
      done
      echo "[*ERROR*] Versionhallintaa ei löydety ylähakemistoista"
      echo "Alusta versionhallinta komennolla: $ ohtuv init"
    fi

# Komentoa ei löytnyt
else
  echo "[*ERROR*] Komentoa ei löytnyt. Tarkista kom"
  echo "$ ohtuv init >> Alustaa versionhallinnan"
  echo "$ ohtuv save [filename] >> Tallentaa tiedoston versionhallintaan"
  echo "$ ohtuv restore [date] [filename] >> Palauttaa tiedoston versionhallinnasta"
fi

echo ""
